spring:
    data: 
        mongodb:
            authentication-database: admin
            database: lavanda 
            host: localhost 
            password:  example
            port: 27017 
            username: root
filebot:
    path: src/main/resources/filebot/            